server:
  port: 8090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wms?serverTimezone=GMT%2b8&useSSL=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 52780
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启日志输出
#    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl #关闭日志输出
#  mapper-locations: classpath:mybatis/*.xml  # xml文件的位置配置
#  type-aliases-package: sm.pojo        # 别名